### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by aragon999** [fionera/Papertowel#1]
I think there should be a uniform naming convention regarding singular/plural, for all folders located in `/src`. Or what were the thoughts, behind the current naming?

I find it often very confusing, when singular/plural is mixed like this, since you always need to look, if the specific folder (and of course the namespace) is in plural or singular.

**Comment by fionera** [comment]
I also thougt about this because its very weird. Symfony Make created the following Folders:

```
Controller
Entity
EventListeners
Migrations
Repository
```

I only created these Folders and made them in Plural because for me it makes more sense when they are in Plural:

```
Services
Components
```
